* Finding the code
What the paper discusses is basically a validation of a general method and library for computing hydrodynamic interactions in systems composed of spherical particles. The code consists of two parts:

  1. The library, called HYDROLIB, which was published in Comp. Phys. Comm. ([[https://doi.org/10.1016/0010-4655(95)00029-F][Vol. 88, page 327]]). It is written in Fortran 77 and was very portable at the time.

  2. The application programs that define the geometry of the conglomerates of spheres and pass it to HYDROLIB. They were not published.

The paper describing HYDROLIB says
#+begin_quote
Catalogue number ADBK.

Program obtainable from: CPC Program Library, Queen's University of Belfast, N. Ireland (see application form in this issue).
#+end_quote

The journal still exists, and its home page contains a link to today's [[https://data.mendeley.com/datasets/journals/00104655][CPC Program Library]], but I have not been able to find HYDROLIB there. I have contacted the "principal editor and library director" with the question of how old software can be retrived.

A few years ago, I found a copy of HYDROLIB on the hard disk of an old computer, and put it [[https://github.com/khinsen/HYDROLIB][on GitHub]]. This is very probably the version that was published in CPC, though I cannot be completely certain. I have since made minor fixes to the setup scripts in order to support more recent compilers, following requests by new users of the library. For the curious: the most recent support request for HYDROLIB is from 2017.

So far I have not been able to find the unpublished application programs. I have two backup tapes in DDS-1 and DDS-2 format from 1998 and 1999 that most probably contain a copy, but so far I have not been able to find a reader for these tapes. Until about 2010, I still had a PC with a tape reader in my office.

* References
[[file:/home/hinsen/Zotero/storage/9537GSQ4/Phys%20Fluids_7_285.pdf][Original article (PDF)]] (local file)
[[/home/hinsen/Zotero/storage/INTW9ZVS/Lasso_Weidman_1986_Stokes%20drag%20on%20hollow%20cylinders%20and%20conglomerates.pdf][Experimental reference]] (local file)
[[/home/hinsen/Zotero/storage/RBD48WXU/Hinsen%20-%201995%20-%20HYDROLIB%20a%20library%20for%20the%20evaluation%20of%20hydrodyn.pdf][HYDROLIB paper]] (local file)

